# Generated by Django 5.0.7 on 2024-08-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picvits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
